project_id = "wtfspzvcetxmcfftwonq"

[functions.process-note]
verify_jwt = false

[functions.dg-token]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.generate-whatsapp-link]
verify_jwt = true